sudo: required
dist: trusty

language: generic

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo add-apt-repository -y ppa:plt/racket
  - sudo apt-get update
  - sudo apt-get install -y ghc-7.10.3 python3.5 racket gcc make gawk grep cloc

script:
  - make
